#!/bin/bash

echo "🔬 DEEP DIAGNOSTIC: Command Registration Analysis"
echo "==============================================="
echo ""

echo "🚨 ROOT CAUSE ANALYSIS"
echo "====================="
echo ""
echo "The 'command extension.explainCode not found' error indicates one of these issues:"
echo ""
echo "1. Extension NOT INSTALLED/ACTIVATED properly"
echo "2. Command registration FAILED during activation"
echo "3. VS Code extension host CRASHED during activation"
echo "4. Extension CONFLICTS preventing proper registration"
echo "5. VS Code VERSION COMPATIBILITY issue"
echo ""

echo "📊 CURRENT EVIDENCE:"
echo "==================="
echo ""
echo "✅ TypeScript compiles without errors"
echo "✅ Command 'extension.explainCode' exists in compiled JavaScript (line 268)"
echo "✅ Activate function is properly exported"  
echo "✅ Package.json has correct command declarations"
echo "✅ Activation events include 'onCommand:extension.explainCode'"
echo ""
echo "❓ MISSING EVIDENCE:"
echo "==================="
echo ""
echo "❓ Is extension actually installed in VS Code?"
echo "❓ Does activate() function execute at all?"
echo "❓ Are there JavaScript runtime errors during activation?"
echo "❓ Is there extension host crash during command registration?"
echo ""

echo "🔍 INVESTIGATION STEPS:"
echo "======================"
echo ""

echo "STEP 1: VERIFY EXTENSION INSTALLATION"
echo "-------------------------------------"
echo ""
echo "Execute these commands in VS Code:"
echo ""
echo "1. Cmd+Shift+X (Extensions panel)"
echo "2. Search: 'CodIn'"
echo ""
echo "Expected results:"
echo "✅ Shows 'CodIn - AI Code Explainer v1.2.1'"
echo "✅ Extension status shows 'Enabled'"
echo "❌ If NOT visible → Extension not installed"
echo "❌ If shows 'Disabled' → Extension disabled"
echo ""

echo "STEP 2: CHECK EXTENSION ACTIVATION"
echo "----------------------------------"
echo ""
echo "1. Open Developer Console: Cmd+Option+I"
echo "2. Go to Console tab"
echo "3. Clear console (trash icon)"
echo "4. Reload VS Code: Cmd+Shift+P → 'Developer: Reload Window'"
echo "5. Watch console during reload"
echo ""
echo "Expected activation logs:"
echo "✅ 'CodIn extension is being activated...'"
echo "✅ 'CodIn extension activated successfully! Commands registered:'"
echo "✅ '- extension.explainCode'"
echo ""
echo "Error scenarios:"
echo "❌ No CodIn messages → Extension not activating"
echo "❌ 'Extension host terminated' → Extension crashed during activation"
echo "❌ JavaScript errors → Runtime errors preventing activation"
echo ""

echo "STEP 3: MANUAL COMMAND CHECK"
echo "----------------------------"
echo ""
echo "After extension loads, test command registration:"
echo ""
echo "1. Open Console: Cmd+Option+I"
echo "2. In Console tab, type this JavaScript:"
echo ""
echo "   vscode.commands.getCommands().then(commands => {"
echo "       console.log('CodIn commands found:', commands.filter(c => c.includes('extension.')));"
echo "   });"
echo ""
echo "Expected result:"
echo "✅ Should list: extension.explainCode, extension.setApiKey, etc."
echo "❌ If empty → Commands not registered"
echo ""

echo "STEP 4: TEST COMMAND EXECUTION"
echo "------------------------------"
echo ""
echo "1. In Console, manually execute command:"
echo ""
echo "   vscode.commands.executeCommand('extension.explainCode');"
echo ""
echo "Expected results:"
echo "✅ Command executes (may show 'No code selected' message)"
echo "❌ 'command not found' → Command registration completely failed"
echo ""

echo "🔧 POTENTIAL SOLUTIONS:"
echo "======================="
echo ""

echo "SOLUTION 1: CLEAN REINSTALL"
echo "---------------------------"
echo ""
echo "If extension shows as installed but not working:"
echo ""
echo "1. Completely uninstall: Cmd+Shift+X → Search 'CodIn' → Uninstall"
echo "2. Restart VS Code completely (Quit and reopen)"
echo "3. Install fresh: Cmd+Shift+P → 'Install from VSIX' → codin-1.2.1.vsix"
echo "4. Restart VS Code again"
echo "5. Check activation logs in Console"
echo ""

echo "SOLUTION 2: EXTENSION HOST RESET"
echo "--------------------------------"
echo ""
echo "If extension host is corrupted:"
echo ""
echo "1. Cmd+Shift+P → 'Developer: Restart Extension Host'"
echo "2. Wait for restart"
echo "3. Check if commands become available"
echo ""

echo "SOLUTION 3: VS CODE CACHE CLEAR"
echo "-------------------------------"
echo ""
echo "If VS Code extension cache is corrupted:"
echo ""
echo "1. Close VS Code completely"
echo "2. Delete cache: rm -rf ~/.vscode/extensions/ms-vscode.vscode-typescript-next*"
echo "3. Delete workspace cache: rm -rf ~/.vscode/workspace*"
echo "4. Restart VS Code"
echo "5. Reinstall extension"
echo ""

echo "SOLUTION 4: CONFLICTING EXTENSIONS"
echo "----------------------------------"
echo ""
echo "If other extensions interfere:"
echo ""
echo "1. Disable ALL other extensions: Cmd+Shift+X → Disable all"
echo "2. Restart VS Code: Cmd+Shift+P → 'Developer: Reload Window'"
echo "3. Test CodIn commands"
echo "4. If it works, re-enable extensions one by one to find conflict"
echo ""

echo "🎯 CRITICAL DEBUG COMMANDS:"
echo "==========================="
echo ""
echo "Run these in VS Code Developer Console to diagnose:"
echo ""
echo "1. Check all commands:"
echo "   vscode.commands.getCommands().then(c => console.log(c.filter(cmd => cmd.includes('extension'))));"
echo ""
echo "2. Check extension status:"
echo "   vscode.extensions.all.forEach(ext => console.log(\`\${ext.id}: \${ext.isActive}\`));"
echo ""
echo "3. Try manual activation:"
echo "   vscode.extensions.getExtension('semicolonailabs.codin').activate();"
echo ""
echo "4. Check for activation errors:"
echo "   console.error('Last errors:', console);"
echo ""

echo "📋 SPECIFIC INVESTIGATION TASKS:"
echo "================================"
echo ""
echo "Please run each step and report results:"
echo ""
echo "[ ] Step 1: Extension visible in Extensions panel?"
echo "[ ] Step 2: Activation logs appear in console?"
echo "[ ] Step 3: Commands listed when checking manually?"
echo "[ ] Step 4: Manual command execution works?"
echo ""
echo "Then try solutions based on where the failure occurs."
echo ""

echo "🚨 HIGH PROBABILITY CAUSES:"
echo "==========================="
echo ""
echo "Based on persistent 'command not found' with proper compilation:"
echo ""
echo "1. 🎯 MOST LIKELY: Extension activation FAILS silently"
echo "   → Check Developer Console for JavaScript errors"
echo "   → Extension may crash during startup"
echo ""
echo "2. 🎯 SECOND LIKELY: Extension HOST issues"
echo "   → VS Code extension host crashes/restarts"
echo "   → Commands get unregistered after registration"
echo ""
echo "3. 🎯 THIRD LIKELY: Installation/Cache corruption"
echo "   → Extension files corrupted during installation"
echo "   → VS Code cache conflicts"
echo ""

echo "The fact that compilation is correct but runtime fails suggests"
echo "either activation failure or extension host instability."
echo ""
echo "🔬 START WITH CONSOLE DEBUGGING TO IDENTIFY EXACT FAILURE POINT!"
