#!/bin/bash

echo "🌍 Installing CodIn v1.1.0 - Multi-Language Edition!"
echo "=================================================="
echo ""

echo "📦 Package Info:"
echo "- Version: 1.1.0"
echo "- Features: 15 Language Support"
echo "- Size: ~816 KB"
echo "- New Commands: Language Selection"
echo ""

echo "🎯 Installation Methods:"
echo ""

echo "📋 Method 1: VS Code Extensions Panel"
echo "1. Open VS Code"
echo "2. Press Cmd+Shift+X (Extensions)"
echo "3. Click '...' menu → 'Install from VSIX'"
echo "4. Select: codin-1.1.0.vsix"
echo "5. Click 'Install'"
echo ""

echo "📋 Method 2: Command Palette"
echo "1. Press Cmd+Shift+P"
echo "2. Type: 'Extensions: Install from VSIX'"
echo "3. Select: codin-1.1.0.vsix"
echo "4. Reload window when prompted"
echo ""

echo "🧪 Quick Test After Install:"
echo "1. Open factorial.py"
echo "2. Press Cmd+Shift+P"
echo "3. Type: 'CodIn: Select Explanation Language'"
echo "4. Choose Bengali/Arabic/Spanish/etc."
echo "5. Select some code"
echo "6. Click floating '🤖 Explain Code' button"
echo "7. See explanation in your chosen language!"
echo ""

echo "🌟 New Features to Try:"
echo "✅ 15 languages supported"
echo "✅ Language shown in CodeLens buttons"
echo "✅ Persistent language preferences"
echo "✅ Native AI prompts per language"
echo "✅ Enhanced popup with language indicator"
echo ""

echo "⚙️ Settings to Configure:"
echo "• Press Cmd+, → Search 'codin'"
echo "• Set explanation language"
echo "• Enable/disable language display"
echo "• Configure CodeLens and quick actions"
echo ""

echo "🚀 Ready to install! Choose your method above."
echo "📖 See MULTI-LANGUAGE-GUIDE.md for detailed instructions."
