#!/bin/bash

echo "🧪 CodIn Extension Manual Testing Guide"
echo "======================================"
echo ""
echo "The extension package has been updated with fixes!"
echo "File: codin-1.0.0.vsix (805KB)"
echo ""
echo "📋 TESTING STEPS:"
echo ""
echo "1️⃣ Install the extension:"
echo "   Open VS Code → Extensions tab → ... menu → 'Install from VSIX'"
echo "   Select: codin-1.0.0.vsix"
echo ""
echo "2️⃣ Open test workspace:"
echo "   File → Open Folder → Select: test-workspace/"
echo ""
echo "3️⃣ Test the feature:"
echo "   a) Open bst.js file"
echo "   b) SELECT some code (highlight with mouse)"
echo "   c) RIGHT-CLICK on selected code"
echo "   d) Look for 'CodIn: Explain Code' in menu"
echo ""
echo "4️⃣ Alternative testing:"
echo "   a) Select code"
echo "   b) Press Cmd+Shift+P (or Ctrl+Shift+P)"
echo "   c) Type 'CodIn: Explain Code'"
echo "   d) Press Enter"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo ""
echo "❌ If menu option doesn't appear:"
echo "   • Make sure text is SELECTED first"
echo "   • Try: Cmd+Shift+P → 'Developer: Reload Window'"
echo "   • Check: View → Output → Extensions"
echo ""
echo "❌ If extension not found:"
echo "   • Check: Extensions tab for 'CodIn - AI Code Explainer'"
echo "   • Try installing again"
echo ""
echo "❌ If API errors:"
echo "   • Verify .env file has: OPENAI_API_KEY=sk-..."
echo "   • Check API key is valid"
echo ""
echo "✅ EXPECTED RESULT:"
echo "   • Progress notification appears"
echo "   • New panel opens with code explanation"
echo "   • Shows selected code + AI explanation"
echo ""
echo "📄 For detailed troubleshooting, see: TROUBLESHOOTING.md"
