name: Feature Request
description: Suggest an idea for CodIn
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for CodIn! 
        
        Please search existing issues to see if your feature has already been requested.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like CodIn to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches might include..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Code Explanation
        - Language Support
        - User Interface
        - API Integration
        - Performance
        - Security
        - Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low (Nice to have)
        - Medium (Would improve workflow)
        - High (Essential for my use case)
        - Critical (Blocking current functionality)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      options:
        - label: I have specific implementation ideas
        - label: I am willing to contribute code for this feature
        - label: I am willing to help with testing
        - label: I am willing to help with documentation

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: If you have specific ideas about implementation, please share them
      placeholder: "This could be implemented by..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. When working on large codebases...
        2. When explaining code to team members...
        3. When learning new programming concepts...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: "For example, if I select a React component..."

  - type: checkboxes
    id: related-tools
    attributes:
      label: Related Tools
      description: Are there similar features in other tools that inspired this request?
      options:
        - label: Similar feature exists in another VS Code extension
        - label: Similar feature exists in another IDE or editor
        - label: Similar feature exists in other AI tools
        - label: This is a completely new idea

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: "Screenshots, mockups, links to similar features, etc..."
